### ISSUE TITLE
Define event to report session abandonment

### ISSUE THREAD

**Issue by tonihei** [cta-standards/R4WG20-QoE-Metrics#12]
If a user abandons a session during playback at any point, there is no event we could currently report. _playbackFail_ only applies to failures and _playbackFinish_ only applies to the natural end of media content.

**Comment by gheikkila** [comment]
I think we earlier discussed this, and concluded that we can never expect that e.g. a browser client will send any "end event" if the window is just closed.

**Comment by tonihei** [comment]
There is some explanation about "incomplete session termination" and that we can only use anything up to the last reported event. However, in cases where we know that the session is abandoned, it would make sense to send an event for that. Many non-browser clients are able to that and even browser clients can do that if the session abandonment happens within one page.

**Comment by mlevine84** [comment]
WG agrees with Gunnar's comment and because the event is not universally available across all browsers and devices it is not enforceable.
