### ISSUE TITLE
Definition of initialStartupTime needs to take into account ad playback

### ISSUE THREAD

**Issue by tonihei** [cta-standards/R4WG20-QoE-Metrics#13]
initialStartupTime on p18 is currently defined for cases where no preroll or midroll ad is played.

Based on the diagrams in the appendix, the actual definition consists of 2 parts:
1. The time between playbackRequest and the first adBreakStart.
2. The total time between ALL adBreakEnd and playbackStart events.

and only in absence of these two: the time between playbackRequest and playbackStart.

**Comment by gheikkila** [comment]
adBreakStart does not imply that anything is playing, it only signals that there is a change from main content twards ad content. There might still be initial buffeirng going on (now for the ad) before something is actually shown. Thus the initialStartupTime definition in the doc should be correct, it measures from the moment the user wants to play something, until something starts to play on the screen.

After the initial startup, if there are other playback interruptions (even between successive ads), these are not treated as "initial", but counted as rebufferings. Note that rebufferings can happen in or between ads as well as in the main content.

**Comment by tonihei** [comment]
Just for clarification:
1. What is the initialStartupTime with preroll ads? Does it include the entire ad because the content only starts afterwards?
2. The drawings have multiple periods between "playbackRequest" and "playbackStart", and these periods are all marked as "starting up". This suggests they are meant to be included in the startup time. Can these drawings be amended to reflect that "starting up" only applies to the initial phase and the rest counts as rebuffering?

**Comment by mlevine84** [comment]
1. No, InitialStartupTime does not include the duration of the preroll ad. IntialStartupTime is from when the user requests content to when preroll ad starts to play.

2. The drawings are accurately capturing what we are intending. However the WG agrees to provide additional text to clarify the calculations.

**Comment by mlevine84** [comment]
2. Gunnar agreed to submit a proposal to WG.

**Comment by mlevine84** [comment]
First comment has been addressed in CTA-2066.

**Comment by njadia** [comment]
@njadia Update the diagram for "Playback with 2 ads in succession" with:

- Add initial startup time represented in the diagram
- update initial start up time formula to clarify "first" playback start - "first" playback request.
- update the diagram to include the stalling instead of starting for the subsequent occurrences.

**Comment by njadia** [comment]
Completed, please close.

**Comment by mlevine84** [comment]
Action: Neel to update the notes section on the diagram included in appendix regarding sub sequence startup times. - CLOSED

Note: InitialStartupTime metric only includes the duration marked as "initial startup". The subsequent "startup" duration in the diagram above can be used to create additional metrics beyond the fundamental set of metrics targeted for this version of the spec.

WG agreed to add the "note" to each appropriate diagram.
