### ISSUE TITLE
Metric on buffer fill

### ISSUE THREAD

**Issue by crittlc** [cta-standards/R4WG20-QoE-Metrics#15]
One of the parameters which may give valuable information on A/V streaming QoE is the variation in time of buffer fill, i.e., the amount of data (or the amount of video seconds, i.e., buffered_data_bytes devided by played_bit_rate) currently stored in the client buffer. When this buffer fill becomes 0, player stalls.

So, to complement (and anticipate) the metrics on rebuffering, it would be useful to have also a value of "buffered_video_seconds".

**Comment by gheikkila** [comment]
How would this metric be used, and by what entity? Note that the scope of the standard is to monitor the streaming sessions, not to actively change or improve the ongoing session.

**Comment by prasadnadig** [comment]
Relevant to consider; in someways, this is indicative of whether downloads are catching up with playback with the buffer having enough to avoid a stall. I recall earlier working group sessions where playback speed was discussed as that could dictate required buffer fill rate.

**Comment by mlevine84** [comment]
We agree this is a useful property, especially for diagnostic purposes, but it does not tie directly into one of the metrics currently defined in the spec. Even though it is useful, we are trying to minimize the amount of properties in the initial version of the spec.
