### ISSUE TITLE
More detailed error messages

### ISSUE THREAD

**Issue by bramtul** [cta-standards/R4WG20-QoE-Metrics#16]
Some more detailed error messages would be helpful, for example having different error events for critical and non-critical errors (those that actually reduce the experience in the spec defined as playbackFail) from those that are recoverable interruption without reducing the actual experience (this could be in the form of a playbackError event).

**Comment by mlevine84** [comment]
There are many potential error messages which might be generated by the player. The WG has limited the error messages and events relevant to metrics defined in the spec.
