### ISSUE TITLE
Technical and business Playback Failure Percentage

### ISSUE THREAD

**Issue by bramtul** [cta-standards/R4WG20-QoE-Metrics#17]
A distinction could be made in the Playback Failure Percentage metric between technical errors (e.g. decoding failed) and business logic related errors (geographic restrictions, token expiration, etc.).

**Comment by gheikkila** [comment]
The main problem is how much to standardize, as the more details added, the more complex a compliant implementation will be...

**Comment by mlevine84** [comment]
Duplicate being addressed in Comment # 22 bullet point 2.
