### ISSUE TITLE
Redoing Figure 1 - Comment made by John Simmons

### ISSUE THREAD

**Issue by mlevine84** [cta-standards/R4WG20-QoE-Metrics#19]
Show all actual components of playback (media player is but one), showing all events, specifically who generates the event (often not the media player). Then I would write a scope section identifying precisely what is in and out of scope for the spec.

**Comment by mlevine84** [comment]
5/8/19: WG20 sent Simmons an email asking him for clarification on which component is he referring to.

**Comment by johnsim** [comment]
1) I see no reason to include any components in Figure 1 that do not play a specified role in QoE determination. For example, “operating system”.
2) Most real media players will get some of the properties associated with events from a component that is not strictly speaking the “media player”. For example, if the prototypical media player is a JavaScript app using a browsers controls, and it is using media source extensions (MSE), then some of the events are simply unknown to the media player. 
3) By "Scope" I mean what components include SHALL and SHOULD statements in the spec. I would like Figure 1 to have a "boxification" of all components which are in scope. 
4) It is important to have a sufficiently granular notion of "media player", sufficient to the discussion of where QoE measures will come from. In practice some parts of media playback are handled by different parts of the device; e.g. hardware codec processing or browser buffering of media segments. Using the HTML5 EME/MSE model as a prime example, some parsing will take place in the JavaScript "player", while other actions will take place in the underlying media stack provided either in the browser or in the operating system. 
5) After boxification, Figure 1 could then show the interaction of components. Collecting the QoE data from various subcomponents of playback is the goal. 
6) In the prototypical HTML5 EME/MSE playback model, the model likely to be common across the industry, collecting some of that data may require changes to HTML5 in the W3C - perhaps using the proposed DataCue API, under discussion in the WICG, to collect QoE data from the browser and/or the underlying platform.

**Comment by mlevine84** [comment]
1. WG agreed to keep the component operation system in Figure 1 to provide the context of execution environment for the media player and analytics agent. This will be addressed as part of issue #21.

2. WG agrees with the feedback. The intention of Figure 1 is to provide a conceptualized view of the stream application. WG will relabel the media player to "Media Player/Media Framework" (Will will make the change)

3. WG's intention with Figure 1 is to provide conceptual view of media player and analytic agent interaction. WG does not intend to specify exact media player components to be involved on every device (Phone, tablet, etc.) The current Figure 1 serves the intended purpose and includes the necessary components.  Figure 1 is intended to be non-normative but descriptive. 

4. Addressed in comment 3 response. 

5. Addressed in comment 3 response. 

6. Addressed in comment 3 response.

**Comment by wilaw** [comment]
Change (2) has been completed. I attached the revised png to this issue. The master .pptx that was used to generate the image has been uploaded to https://standards.cta.tech/apps/org/workgroup/r4wg20/download.php/27065/r4wg20-_-r_graphics%20for%20metrics%20doc-v2.pptx 
![graphics for metrics doc-v2](https://user-images.githubusercontent.com/2762250/60409250-1bde6b00-9bc3-11e9-9923-7939c53712b4.png)

**Comment by wilaw** [comment]
Used this image to update the google doc. https://docs.google.com/document/d/1q6_8DPpidUHm3Pu2KXX588auAEEGaQUWO9IJHAoE17k/edit

**Comment by njadia** [comment]
@mlevine84  Please close this ticket as this action item has been completed by @wilaw
