### ISSUE TITLE
Broken link to DASH IF Position Paper

### ISSUE THREAD

**Issue by johnsim** [cta-standards/R4WG20-QoE-Metrics#2]
Informative References - https://dashif.org/wp-content/uploads/2016/10/ProposedMediaMetricsforSegmentedMediaDelivery-r12.pdf 
is a broken link

**Comment by mbergman42** [comment]
Should be changed to [https://dashif.org/docs/ProposedMediaMetricsforSegmentedMediaDelivery-r12.pdf](https://dashif.org/docs/ProposedMediaMetricsforSegmentedMediaDelivery-r12.pdf).

**Comment by mlevine84** [comment]
The link has been fixed and the document has been updated on GitHub.
