### ISSUE TITLE
New Scope Section - Comment made by John Simmons

### ISSUE THREAD

**Issue by mlevine84** [cta-standards/R4WG20-QoE-Metrics#20]
I would like to see a scope section – making it clear what the spec is defining. Somewhat implied in the Introduction, but needs to be very clear. The pp. beginning “the goal of this specification is to define a set of player events, …” captures one part of it, but since this is intended to be used by “across systems, players and analytic vendors”, it is unclear how that is accomplished unless you define both the syntax and semantics – a standardized namespace for these events, properties and metrics.

**Comment by gheikkila** [comment]
I think this is touching on the same topic as the 3GPP "formal API" question in issue #24

**Comment by mlevine84** [comment]
Duplicate request of comment #24 and WG will address it.
