### ISSUE TITLE
Comments made by Broadspeak

### ISSUE THREAD

**Issue by mlevine84** [cta-standards/R4WG20-QoE-Metrics#23]
I have a question regarding the Doc. Number:  CTA-2066. Although the document refers to ITU-T P1203 specification, the standardized playback session metrics does contain playbackStallDuration but not the way P.1203.3 envisaged it. In P.1203.3 it is a weighted sum of all stall events (totalStallLen). In addition the P.1203.3 model requires the Average stall interval (avgStallInterval) that is not part of the CTA-2066 session metrics list although it seems possible to build the metrics thanks to the standardized list of events. 

The way  ITU-T SG12 develop their QOE related specifications makes them rather trustable; I wonder why CTA did not consider the ITU-T 1203(.x) specs more precisely.

**Comment by mlevine84** [comment]
Response to Broadspeak - P.1203 is calculated based on the standardized events and properties and no further metrics are needed.

**Comment by mlevine84** [comment]
Assign to Gunnar. If we want to reference 1203.3 in the future WG agrees we need to add new properties and events.

**Comment by njadia** [comment]
Current description in the spec is clear enough to address the query. This can be closed @mlevine84
