### ISSUE TITLE
Comments made by 3GPP

### ISSUE THREAD

**Issue by mlevine84** [cta-standards/R4WG20-QoE-Metrics#24]
•	CTA-2066 defines standardized events and properties (including standardized names), but also states that a player does not need to use the standardized names. Even if an informal name-mapping table is suggested, SA4 believes that mandating use of the standardized names would enhance the usability of the standard. Alternatively, the mapping table might be standardized?

•	We also recognize that there are currently no formal (programmatical) APIs towards the player defined in CTA-2066. SA4 believe that defining such APIs would probably ease correct and unambiguous implementations for different player types and improve interoperability and conformance testing.

•	While properties are typed (e.g. "integer", "float" or "number"), there is no strict definition of the exact data format (16bit/32bit/signed/unsigned etc.). SA4 believe that using exact definitions for the data format would further improve the implementability, especially regarding structured properties or events (if any).

•	In the standardized events clause, CTA-2066 states that "Most events include metadata, which gives necessary details to make the events useful for consistent metrics calculations." However, we cannot find any description of this metadata, or any description of which events that include such metadata?

•	In the properties clause it is stated that "Properties may be scalar or structured. For structured properties it shall also be possible for the analytics client to directly request the value of a single sub-property." However, there doesn't seem to be any structured properties defined?

•	There is currently no defined property for the current playhead position. SA4 believe that adding this property might be useful.

SA4 appreciates the intention and the direction of the draft CTA-2066 specification, and could consider using the approved version as one input in the ongoing 5G Media Streaming work. This work is currently planned to be completed in Q4/2019, with the bulk of the work expected to be done in Q3. 

Thus, in addition to the above comments, SA4 would be interested to know if CTA have defined a future roadmap for CTA-2066, possibly also including descriptions of more formal APIs?

2. Actions:
ACTION:	SA4 kindly ask CTA to take the above information into account, and to inform us about the future plans and roadmap for CTA-2066.

**Comment by mlevine84** [comment]
3GPP Comment 1 - WG cannot mandate the names but could consider a mapping table. Will revisit later. Add language to ensure new APIs introduced by player vendors comply with the CTA spec. 

Comment 2 - Input is valuable to help decide the evolution of the spec. For now we cannot include in current version of the spec.

Comment 3 - Input is valuable to help decide the evolution of the spec. For now we cannot include in current version of the spec.

Comment 4 - WG agreed to remove the sentence from spec based recommendation. 

Comment 5 - WG agreed to remove the sentence from spec based recommendation.

Comment 6 - WG agreed to remove definition of playhead because it's not required for metrics calculation.

**Comment by gheikkila** [comment]
Mark, it's not good to use the # sign with numbers, as github interprets these as cross-references to other issues. So you get a bit confused when reading other issues which have a cross-reference from the 3GPP issue (when actually there is none). So remove the # sign...

**Comment by mlevine84** [comment]
Comment 1. Assigned to Steve Hefferenan 

Comments 4,5,6: Levine to review to make sure they have been completed.

**Comment by njadia** [comment]
July 10, 2019 - @heff will provide a proposal to add the requested information in the google doc.

**Comment by njadia** [comment]
Added "Player Event & Properties Mapping" on page 24 as a response to comment # 1.
