### ISSUE TITLE
Consider adding "Average wait time percentage" (or replace "average stalled time percentage")

### ISSUE THREAD

**Issue by tonihei** [cta-standards/R4WG20-QoE-Metrics#6]
For video services playing very short videos, the "average stalled time percentage" is likely to be much less than the percentage of watched time spent waiting for the startup time. 

A potentially better and more robust metric is the "average wait time percentage" (name TBD) which includes all wait times (startup, stalls, seeks) as a percentage of the watched time (wait times+play time).

**Comment by gheikkila** [comment]
Yes, in principle you are correct. Especially for short clips there is a clear tradeoff between the start time and any rebuffering during the clip. With long enough start time there will never be any mid-content rebufferings.

**Comment by mlevine84** [comment]
WG believes the viewer impact of initial start up and re-buffering time is different and there are metrics defined in the spec to calculate the requested information. By combining these metrics, the total waiting time can also be analyzed. Hence WG recommends not to replace or add a new metric.
