### ISSUE TITLE
Replace or complement "average playback bitrate" by "average playback resolution"

### ISSUE THREAD

**Issue by tonihei** [cta-standards/R4WG20-QoE-Metrics#7]
The perceived Quality of Experience is not necessarily related to the bitrate of the played streams:
- Improvements in encoding algorithms can easily reduce the bitrate while keeping the quality the same and it is very difficult to compare the bitrates across different encodings. 
- The bitrate is more likely to be exponential to the perceived quality. For example, the perceived quality only doubles when increasing from 512kbps, 540p to 2Mbps 1080p. This leads to the problem that the average is mostly influenced by the large bitrates, whereas the most improvements in perceived quality are probably made by making changes in the lower bitrate/resolution ranges which are difficult to see with such a metric.

A potentially better option would be to use the resolution height in pixels:
- This is independent of the encoding algorithm
- And better reflects changes in lower qualities as the linearity between resolution and perceived quality means that the influence on the average is the same for all format improvements.

**Comment by gheikkila** [comment]
It's an interesting question, but not with a simple answer. Yes, using the resolution (height) as a quality indicator would be possible, but it's still not a one-to-one mapping towards quality (and then there is the question on what "quality scale" is used). 

The more complex answer to this question is to instead use the (currently optional) ITU-T P.1203 standard, see the chapter "Video & Audio Quality Metrics".

**Comment by mlevine84** [comment]
WG acknowledge average bitrate is an imperfect measure of the perceived quality but switching to a metric taking resolution into account will not yield improvement to the measure of the perceived quality either. Hence WG decides to stay with the current metric in the spec.
