### ISSUE TITLE
Missing aspects of "Video and audio quality"

### ISSUE THREAD

**Issue by tonihei** [cta-standards/R4WG20-QoE-Metrics#8]
The category of "video and audio quality" is so far only defined by the metric "Average Playback Bitrate". This leaves out some important aspects of perceived video and audio quality:
1. Quality changed during playback: Switching quality up and down (especially for video) is noticeable by the user and reduces the perceived quality compared to a steady format selection.
2. Playback may not be smooth due to device limitations and playback problems. Typical examples are audio underruns and dropped video frames.

Both aspects should preferably be captured by some metric to provide a full picture.

**Comment by gheikkila** [comment]
The chapter "Video & Audio Quality Metrics" covers the ITU-T standard P.1203, which does capture these effects. It's currently just an optional metric, as the implementation is a bit more complex than for the other metrics.

**Comment by mlevine84** [comment]
WG acknowledge the point raised and the request has been debated extensively within WG. WG has decided to address the point raised in future version of the spec.
