### ISSUE TITLE
Definition of "watched time" on page 18 is inaccurate

### ISSUE THREAD

**Issue by tonihei** [cta-standards/R4WG20-QoE-Metrics#9]
There are two issues:

1. The watched time should be defined in milliseconds as the other metrics. This would also remove the need to define decimal places.

2. The definition says it's the sum of time between (a) _playbackRequest_ and (b) _playbackPause, playbackFinish, playbackFail_. I'd argue (a) should be _playbackRequest_ and _playbackStart_. Otherwise all "restart" scenarios are not really captures as if only expect one _playbackRequest_ event.

**Comment by gheikkila** [comment]
The intention is to capture the time the user is watching, which should be between the (first) playbackRequest (i.e. usually when the user press "Play") and the next pause/finish/fail. If there are multiple playbackRequest events (without intervening pause/finish/fail, like if the user is seeking) these should probably not be used to mark the start of watched time.

The playbackStart event is not related to the user action, but only to when rendering of a content starts, so it's not related to when the user started to watch. Thus it should not be used in the calculation of watched time.

**Comment by mlevine84** [comment]
For 1, WG will consider the request to use milliseconds and will be addressed with comment #22 

For 2, WG agrees with Gunnar's response above to address the raised concern.
